name: Daily Commit

on:
  schedule:
    - cron: '0 10 * * *' # Runs every day at 10:00 AM UTC

jobs:
  daily_commit_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create Timestamp File
        run: |
          date > timestamp.txt
          git config --global user.email "23f1001029@ds.study.iitm.ac.in"
          git config --global user.name "GitHub Actions"

      - name: Commit Changes
        run: |
          git add timestamp.txt
          git commit -m "Daily commit $(date)"
          git push origin main

      - name: Verify Commit within 5 Minutes
        run: |
          # Get the workflow run ID
          WORKFLOW_RUN_ID="${GITHUB_RUN_ID}"

          # Use GitHub API to get the commit SHA
          COMMIT_SHA=$(curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runs/${WORKFLOW_RUN_ID}/jobs" | jq -r '.jobs[] | select(.name == "Commit Changes") | .steps[] | select(.name == "Commit Changes") | .conclusion | .head_sha')

          # Handle cases where the API call fails or the commit SHA is not found
          if [[ -z "$COMMIT_SHA" ]]; then
            echo "Error: Could not retrieve commit SHA from GitHub API."
            exit 1
          fi

          # Get the timestamp of the commit
          COMMIT_TIMESTAMP=$(git show -s --format=%ct $COMMIT_SHA)

          # Get the workflow run started time (using GITHUB_RUN_ID instead of attempt)
          WORKFLOW_START_TIME=$(curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runs/${WORKFLOW_RUN_ID}" | jq -r '.created_at')
          WORKFLOW_START_TIME=$(date -d "$WORKFLOW_START_TIME" +%s)


          # Calculate the difference in seconds
          TIME_DIFF=$(( $COMMIT_TIMESTAMP - $WORKFLOW_START_TIME ))

          # Check if the time difference is within 5 minutes (300 seconds)
          if [[ $TIME_DIFF -lt 300 && $TIME_DIFF -ge 0 ]]; then
             echo "Commit created successfully within 5 minutes of workflow run."
          else
            echo "Error: Commit was not created within 5 minutes of workflow run."
            echo "Time difference: $TIME_DIFF seconds"
            echo "Commit Timestamp: $COMMIT_TIMESTAMP"
            echo "Workflow Start Time: $WORKFLOW_START_TIME"
            exit 1
          fi
